### ISSUE TITLE
Support HTTPS

### ISSUE THREAD

**Issue by marcecj** [HoerTech-gGmbH/doasvm-visualizer#2]
(Originally T762 in the openMHA Phabricator, this text copied verbatim from there.)

Access to webcams and microphones will only work in HTTPS websites in newer browsers (Firefox starting with 69.0 and partially in 68.0 (see [0]) and Chrome starting with 74 IIRC).  However, local connections will still work (i.e., connections to `localhost`).

This means that the usual way of running the demonstrator (everything on one system) should still work in the future.  Furthermore, running MHA on a different system will also still work.  What will **not** work anymore is running the Python server on a different system than the web browser.

This should not be a problem for us or the university, but Hendrik suggested that, while unlikely, an external user might be using this framework and run into this problem.

This task is for documenting this potential issue.

Two potential solutions spring to mind:
- Refer to a reverse-proxy HTTP server (e.g., nginx) which would handle the HTTPS connection while connecting to Python using plain HTTP.
- Serve using HTTPS directly via `tornado` (see the [relevant documentation](https://www.tornadoweb.org/en/stable/httpserver.html?highlight=ssl)).

[0] https://blog.mozilla.org/webrtc/camera-microphone-require-https-in-firefox-68/

**Comment by tobiasherzke** [comment]
Suggestion:

As long as the camera still works for unencrypted localhost connections, then document this and do not try to solve this by switching to https. Chances are very high that self-signed SSL certificates will also be rejected by the same browsers that reject unencrypted connections, if not now then later, and then all the effort spent in autogenerating certificates or documenting how users can do it will have been spent for nothing.

**Comment by marcecj** [comment]
Yeah, the issue title is somewhat misleading, this issue is really just about dealing with the HTTPS change in general, not necessarily supporting HTTPS directly.  My personal preference is very much the first option, which is supposed to be understood as "document this and refer to the possibility of setting up a reverse-proxy if you absolutely need HTTPS".  Since it looks to me like we're in agreement, I'll just go ahead and do that.
